version: '3'

services:
  rest-api:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: challenge
    volumes:
      - ./src:/opt/challenge/src
      - ./tests:/opt/challenge/tests
      - ./log:/opt/challenge/log
      - ./example_payloads/:/opt/challenge/example_payloads
    ports:
      - 8888:8888
    restart: always
    network_mode: host
